# Generated by Django 4.0.2 on 2022-03-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnomina', '0004_alter_cargo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='cedula',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
